### PR TITLE
:lipstick: Remove unused ID attributes

### PR DESCRIPTION
**Pull request by peterblazejewicz**
This is jest re-brushing simple commit to trim down content.
These specific ids have no purpose behind them. For example these forms are not
validated explicitly by client code (during validation), there is no CSS style
matched for them, etc.

Thanks!

### CODE REVIEW

**Comment by Eilon** [comment]
Hi @peterblazejewicz I think these are useful for testing, even if they're not used directly in the template. They also make it more convenient to style things later by just adding CSS. So, I think given that it's fairly harmless, and potentially useful, it's ok to keep them. Thanks!

**Comment by peterblazejewicz** [comment]
@Eilon 
Yes, the QA ids is a valid point,

For above reason:
note to myself, for the records:
- find and add ids to all those forms without IDs (mvc with auth):
```cshtml
<form asp-action="ForgotPassword" method="post">
<form asp-route-returnurl="@ViewData["ReturnUrl"]" method="post">
<form method="post" asp-route-returnUrl="@ViewData["ReturnUrl"]">
<form asp-action="ExternalLoginConfirmation" asp-route-returnurl="@ViewData["ReturnUrl"]" method="post">
```

**Comment by peterblazejewicz** [comment]
@Eilon 
Bear with me, but where I could find now the templates (Razor) that comes as part of shared content for `ASP.NET MVC` templates? Kind of older:
https://github.com/aspnet/Templates/tree/dev/template_feed/Microsoft.DotNet.Web.ProjectTemplates.2.0/content/StarterWeb-CSharp/Views/Manage
TIA

**Comment by Eilon** [comment]
@peterblazejewicz for the 2.1 release we moved almost all the "individual authentication" code and markup into a library NUPKG.

Here's the work item: https://github.com/aspnet/Identity/issues/1473
And this is where the code lives now: https://github.com/aspnet/Identity/tree/dev/src/UI

**Comment by peterblazejewicz** [comment]
Thx!

**Pull request closed without merging**
