### PR TITLE
Fix package metadata to match default settings for aspnetcore

### PR DESCRIPTION
**Pull request by natemcmaster**
Part of https://github.com/aspnet/Coherence-Signed/issues/789.

Templates packages had the wrong metadata for project url, copyright, repository url, etc. This unifies metadata to what Internal.AspNetCore.Sdk defines.

### CODE REVIEW

**Comment by natemcmaster** [comment]
@jbagga are there known issues in templates tests? This PR is not passing AppVeyor or Travis or locally

**Comment by jbagga** [comment]
Appveyor is flaky. Travis has known issues. But they should build locally

**Comment by natemcmaster** [comment]
Ok, I re-ran AppVeyor and it passed. Passed locally too

**Comment by jbagga** [comment]
Spoke to @natemcmaster offline "dotnet pack" is failing because the repositoryCommit is not being correctly populated. Looks good otherwise. I'll approve once I can manually verify template creation.

**Comment by natemcmaster** [comment]
We hit this: https://github.com/NuGet/Home/issues/6722. I'll make a fix to Internal.AspNetCore.Sdk to workaround it.

**Comment by natemcmaster** [comment]
Oops, premature merge. If you find something I'll revert.

**Pull request merged**
