### PR TITLE
Refresh user signin after updating their profile

### PR DESCRIPTION
**Pull request by Biarity**
That way, the changes are immediately visible.

### CODE REVIEW

**Comment by Eilon** [comment]
I'm not sure if this is necessary because there's a redirect that's about to happen anyway. I feel that even though this API is called, the "system" is overall in a "bad state" because half of it will think the user is the "old" profile, and half of it will think the user is the "new" profile.

@HaoK / @Tratcher / @blowdart - thoughts on this?

**Comment by Tratcher** [comment]
This makes sense. The user has just changed some of their profile information in the database but still has the old values cached as claims in the auth cookie. RefreshSignInAsync issues a new auth cookie with the updated information.

**Comment by HaoK** [comment]
Its safe to call refresh sign in generally to update the claims on the response.  That said, identity doesn't put the phone number of email in the cookie by default, so this shouldn't actually result in any claims being updated

**Comment by blowdart** [comment]
We should add it though, for "correctness" or an illustration of what should eb done.

**Comment by Eilon** [comment]
@jbagga can you review & merge? @Tratcher and @blowdart say it's good, so let's do it.

**Comment by jbagga** [comment]
@Eilon Which milestone is this in?

**Comment by Eilon** [comment]
`2.1.0-preview2`, so just `dev`

**Comment by jbagga** [comment]
The code has moved to Identity UI https://github.com/aspnet/Identity/pull/1615

**Comment by jbagga** [comment]
@Biarity Thanks for the suggestion! The code change has been moved to the new location.

**Comment by dougbu** [comment]
This issue was moved to aspnet/Scaffolding#736

**Pull request closed without merging**
