### PR TITLE
Update EF Core Migrations

### PR DESCRIPTION
**Pull request by bricelam**

### CODE REVIEW

**Comment by Eilon** [comment]
@bricelam who would be best suited to review this? Also, can you update your PR branch? Looks like it's out-of-sync with dev?

**Comment by Eilon** [comment]
@ajcvickers okie dokie I'm assigning this PR to you for tracking.

**Comment by javiercn** [comment]
I'm porting this commit to https://github.com/aspnet/templating/pull/204 as @bricelam is out for the rest of the year and I need it there. /cc: @ajcvickers @Eilon

**Comment by bricelam** [comment]
Updated by #313

**Pull request closed without merging**
