### PR TITLE
Remove string array for shortName alias

### PR DESCRIPTION
**Pull request by jbagga**
The upgrade to the new SDK is still blocked. Reopening #325

### CODE REVIEW

**Comment by jbagga** [comment]
FYI @ryanbrandenburg I will merge once Appveyor/Travis run

**Comment by mikeharder** [comment]
@jbagga : This passed on Travis/Linux, but failed on Travis/Mac and AppVeyor.  Think it's safe to merge to unblock the Templating repo?

**Comment by jbagga** [comment]
@mikeharder Actually @ryanbrandenburg unblocked the SDK upgrade from Update Universe which means I do not need to merge this in at all. With the new SDK there should be no failrues. Right now I am just waiting on approval for https://github.com/aspnet/templating/pull/474 which should unblock Templating.

**Comment by jbagga** [comment]
Closing as the new SDK is now being consumed by our builds and there is no need to revert the use of string array in the template.json

**Pull request closed without merging**
