### PR TITLE
Turn on MaxKeyLengthForKeys in templates

### PR DESCRIPTION
**Pull request by HaoK**
Depends on: https://github.com/aspnet/Identity/pull/1555

Part of: https://github.com/aspnet/templating/issues/62

@javiercn @ajcvickers

### CODE REVIEW

**Comment by javiercn** [comment]
@ajcvickers Shouldn't we update the migrations at the same time?

**Comment by ajcvickers** [comment]
@javiercn The migration needs to be updated, but it doesn't have to be done as part of the same PR.

**Comment by javiercn** [comment]
@ajcvickers Won't this change break dotnet new?

**Comment by ajcvickers** [comment]
@javiercn Break in what way?

**Comment by javiercn** [comment]
@ajcvickers Won't ef tell you that the model is not up to date and you need to generate a new migration?

**Comment by ajcvickers** [comment]
@javiercn Essentially, no. More specifically:
* EF Core doesn't have any mechanism that runs automatically for checking if the model is up-to-date with the database.
  * There is the database error page middleware, but that only kicks in if the application fails. The application should not fail in this case unless it has data that won't fit, which is unlikely, and is an error that would happen later anyway.
* If the user calls add-migration, then a new migration will be scaffolded. But this is true anyway at the moment because the existing migration checked in is not up-to-date anyway.

**Comment by HaoK** [comment]
Updated PR with initial migration updates as well, please re-review

**Comment by HaoK** [comment]
5d2f598c8094f4c0b00e430ddd50512fc32fe3eb

**Pull request closed without merging**
