### PR TITLE
Update jQuery

### PR DESCRIPTION
**Pull request by jbagga**
This reverts commit 382a762a08d072b235cd230c0fd883b3871c5799.

Addresses #18

### CODE REVIEW

**Comment by jbagga** [comment]
I'll also send a PR out for bootstrap later

**Comment by jbagga** [comment]
cc @Eilon for license info

**Comment by Eilon** [comment]
Here are the license instructions to update:

* [x] License notice for HTML5 Boilerplate
   * No change
* [x] License notice for Normalize.css
   * No change
* [x] License notice for css-transitions
   * No change
* [x] License notice for micro-clearfix-hack
   * No change
* [ ] License notice for Bootstrap v3.3.6
   * Change version to v3.3.7
* [ ] License notice for jQuery 2.2.0
   * Change version to v3.3.1
   * Replace license text with EXACT copy of https://raw.githubusercontent.com/jquery/jquery/3.3.1/LICENSE.txt
* [x] License notice for jQuery Validation v1.14.0
   * No change
* [ ] License notice for Json.NET (Newtonsoft.Json)
   * REMOVE entire section (it isn't needed)

**Comment by jbagga** [comment]
@Eilon Made the above changes to THIRD-PARTY-NOTICES file

**Comment by jbagga** [comment]
@mkArtakMSFT FYI

**Pull request merged**
