### PR TITLE
Adding host configurations for F# templates

### PR DESCRIPTION
**Pull request by jbagga**
Patch for 2.0.x 

See https://github.com/aspnet/templating/pull/281#issue-166693279

### CODE REVIEW

**Comment by jbagga** [comment]
cc @Eilon @jmarolf

**Comment by Eilon** [comment]
@jbagga - do we have a bug tracking this for 2.0.7? If not, let's get a new bug tracking it and we can leave it open so that we remember to include it in our patch changes.

**Comment by jbagga** [comment]
@Eilon Filed here https://github.com/aspnet/templating/issues/337

**Comment by jbagga** [comment]
@natemcmaster FYI this is for 2.0.7

**Comment by natemcmaster** [comment]
Once merged, you'll need to manually update the modules/Templating submodule in aspnet/Universe's release/2.0 branch. @jbagga Let me know if you need more details on how to do that.

**Pull request merged**
