### PR TITLE
return ReturnUrl when ExternalLogin fails

### PR DESCRIPTION
**Pull request by jbagga**
Addresses #97

### CODE REVIEW

**Comment by jbagga** [comment]
cc @javiercn

**Comment by Eilon** [comment]
@javiercn can you work with @jbagga on how to test this?

**Comment by javiercn** [comment]
@Eilon Sure. No problem

**Comment by javiercn** [comment]
I'm signing off for now, because testing this is not trivial. But @HaoK should review it.

**Comment by HaoK** [comment]
Looks fine, I think you can probably test it by munging the registered app path for the oauth you set up so it comes back with an error instead of a redirect, like if register the wrong localhost port for your web app with google/facebook

**Comment by HaoK** [comment]
Or if that doesn't work, you can maybe remove something like email from the permissions for google, which I think also causes errors since we always ask for email

**Comment by jbagga** [comment]
The ExternLoginCallback action is not hit if I try the first suggestion. The external login provider errors out and does not return back to my app. Pressing back on the browser takes me back to the login page.

The second suggestion cannot be configured. At least I can't find how to remove email from permissions for Google or Facebook

**Comment by javiercn** [comment]
@HaoK Can't you configure scopes for Google? It should be easy enough to put an incorrect value for the scopes on Google and use that to trigger an alert.

**Comment by HaoK** [comment]
The error flow well end up looking like the other two bugs you filed with fb/twitter when you hit cancel I think.

basically you can add a new scope, like the plus.me like so:
```
               o.Scope.Add("https://www.googleapis.com/auth/plus.login");
```

That will prompt the user to allow or deny, and if you deny it causes and error but that ends up showing up with an access denied exception on the signin-google request as well.  

But looking at this a bit more, I don't think there's any path that leads to the ExternalLoginCallback action getting called with a remoteError, as the built in logic throws an exception, unless they handle the repsonse themselves: https://github.com/aspnet/Security/blob/dev/src/Microsoft.AspNetCore.Authentication/RemoteAuthenticationHandler.cs#L102

**Comment by HaoK** [comment]
So if you just want to test GetExternalLoginInfo failing, you can just delete the Identity.ExternalCookie which would result in that call failing, if you don't have a chance to manually do it, you can just add some code in a middleware at the end that calls SignOut on every request on that scheme.

**Comment by javiercn** [comment]
@HaoK Can you give @jbagga a sample in a gist?
I'm failing to understand too how the middleware goes from receiving the error on the callback to redirecting to the endpoint.

**Comment by jbagga** [comment]
@javiercn @Eilon 

Since there is no 

> path that leads to the `ExternalLoginCallback` action getting called with a `remoteError`, as the built in logic throws an exception,

I tested the other path where `GetExternalLoginInfo` returns null and the return url is preserved

**Comment by HaoK** [comment]
Should we just remove that remoteError parameter/logic since there's no way to trigger it anymore as far as we can tell?

**Comment by javiercn** [comment]
@HaoK I'm ok with that, but you are the expert in here. Could you take a look in depth to make sure that's the case? Should we file a bug in identity for this to track it? (even though is template code).
I think at least it deserves some investigation by someone more familiar with the area before we take action.

**Comment by HaoK** [comment]
Sure file a bug in security, we have one which is tracking the error flows already https://github.com/aspnet/Security/issues/1165 but this one probably deserves a separate issue at least initially

**Comment by jbagga** [comment]
Filed a bug here https://github.com/aspnet/Security/issues/1571

**Pull request merged**
