### PR TITLE
Asp net core vue js spa pkg update

### PR DESCRIPTION
**Pull request by FooBartn**
**Purpose:** 

- Bring packages in package.json up to current with functional webpack config
- Rename components to .vue to take advantage of Vue tooling such as Vetur

**Issue opened and discussed here:** https://github.com/aspnet/JavaScriptServices/issues/1390

### CODE REVIEW

**Comment by Eilon** [comment]
@SteveSandersonMS - per your comment at https://github.com/aspnet/templating/issues/76#issuecomment-340840328, what do you recommend?

**Comment by FooBartn** [comment]
Apologies -- left for the holidays and didn't realize the build didn't pass. Apparently the built in uglify plugin for webpack only supports es5. Needed to grab the updated module and use it instead.

**Comment by Jackchengwang** [comment]
How to add a external package, i.e. moment.js to the spa project?

**Comment by SteveSandersonMS** [comment]
@Eilon I'll move forwards with the templating and JavaScriptServices work items on Wednesday if that's OK.

**Comment by Jackchengwang** [comment]
I got some non-type script based vue components, how to port them to the project created by this template? also I found the vuejs is at version 2.2.2, how to keep the component up-to-date?

**Comment by FooBartn** [comment]
@Jackchengwang 

I think your questions are a probably a bit out of scope for this pull request. I'd probably suggest reading up on node/npm and how to manage package.json. This template is primarily to get people started with asp.net core and vue together in a single page application. The management / use of all the separate pieces is info you'll need to find elsewhere, such as the specific tool documentation or a help forum.

**Comment by SteveSandersonMS** [comment]
Thanks @FooBartn for proposing this!

As it happens, we're now recommending that interested community members ship their own Vue templates separately. We're no longer updating the Vue template in this repo ([info](https://github.com/aspnet/Announcements/issues/289)). Hope that's OK!

**Comment by FooBartn** [comment]
Understood! I'll see what I can do to make my version dotnet new-able :)

**Comment by FooBartn** [comment]
@SteveSandersonMS Do you have any issue with me modifying and re-using the .template.config folder you have there? I would change the groupIdentity, identity, and name/shortname.  If I do so, what would you consider the proper way to author it? Since it was originally written by you guys and for now I have just updates packages etc.. "Microsoft, FooBartn"?

**Comment by SteveSandersonMS** [comment]
@FooBartn That sounds great! Yes, it's OSS, so you're free to fork it and continue. I'm not 100% certain on the licensing requirements but you might have to retain copyright notices or something. Please read the license for details.

**Pull request closed without merging**
