### PR TITLE
Remove tools references and explicit EF.Design reference

### PR DESCRIPTION
**Pull request by jbagga**
Addresses #99 and #357

### CODE REVIEW

**Comment by ajcvickers** [comment]
I will defer to @bricelam on this...

**Comment by jbagga** [comment]
Tests fail with
```
Failed   Templates.Test.MvcTemplateTest.MvcTemplate_IndividualAuth_UsingLocalDB_Works_NetCore
Error Message:
 Assert.Contains() Failure
Not found: Microsoft.EntityFrameworkCore.Tools.DotNet
In value:  <Project Sdk="Microsoft.NET.Sdk.Web">
```

https://ci.appveyor.com/project/aspnetci/templating/build/1.0.416#L288
@bricelam @ajcvickers

**Comment by jbagga** [comment]
Waiting for https://github.com/dotnet/cli/pull/8844 to be merged so the tests can use the CLI command to install dotnet-ef

**Comment by bricelam** [comment]
@ryanbrandenburg Do we have a chicken and egg problem? Does this need to be merged before we can get a build of dotnet-ef that we can insert into the SDK?

**Comment by jbagga** [comment]
Just chatted to @ryanbrandenburg I think if we temporarily disable the tests we can get this change in and get a build for dotnet-ef

Once that's in I can turn the tests back on and fix them cc @bricelam

**Comment by jbagga** [comment]
https://github.com/aspnet/templating/issues/378 tracking re-enabling of auth tests

**Pull request merged**
