### PR TITLE
Fix HttpsPolicy dependency for full framework

### PR DESCRIPTION
**Pull request by jkotalik**
For #150

### CODE REVIEW

**Comment by natemcmaster** [comment]
Add MicrosoftAspNetCoreHttpsPolicyPackageVersion to dependencies.props too, then :shipit:

**Comment by jkotalik** [comment]
Ah shoot, we need to update the tests. All tests are currently using http instead of https clients.

**Comment by SteveSandersonMS** [comment]
@jkotalik Please ensure there's at least one test (per template) that still makes the initial request over `http` so we can verify that it correctly redirects over to `https`.

**Comment by jkotalik** [comment]
@natemcmaster I'm going to merge this for now and fix the launch settings and Https tests in another PR (as this is a compiler blocker).

**Pull request merged**
