### PR TITLE
Fix kestrel urls in launchSettings.json

### PR DESCRIPTION
**Pull request by javiercn**

### CODE REVIEW

**Comment by javiercn** [comment]
Approved verbally

**Comment by javiercn** [comment]
This is done 216e9f62c4f375e15e4a78cbb6aecf0d91850106

**Comment by georgiosd** [comment]
How do we get this working? I tried to make the change but I got an error saying that Kestrel HTTPS can only be configured in code.

**Comment by javiercn** [comment]
@georgiosd What version are you trying to use. This change is for our next release, it's not part of the 2.0.0 release

**Comment by georgiosd** [comment]
Gotcha. I can wait for that. What's your guys ETA on 2.1?

**Pull request closed without merging**
